apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /frontend(/|$)(.*)
        backend:
          service:
            name: books-frontend-service
            port:
              number: 8090
      - pathType: Prefix
        path: /api/books(/|$)(.*)
        backend:
          service:
            name: books-service
            port:
              number: 8090
      - pathType: Prefix
        path: /api/bookstore(/|$)(.*)
        backend:
          service:
            name: bookstore-service
            port:
              number: 8090
