POST http://localhost/api/bookstore/purchase

[
    "Moby Dick; Or, The Whale",
    "Romeo and Juliet",
    "Frankenstein; Or, The Modern Prometheus"
]

###

GET http://localhost:8091/purchased


###

POST http://localhost/api/bookstore/purchase

[
    "Moby Dick; Or, The Whale",
    "Romeo and Juliet",
    "Frankenstein; Or, The Modern Prometheus"
]

###

GET http://localhost/api/bookstore/purchased