apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
data:
  config.yml: |
    server:
      host: "0.0.0.0"
      port: 8090
    client:
      books:
        protocol: "http://"
        host: "books-service.default.svc.cluster.local"
        port: ":8090"
        endpoint: "/books"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
  labels:
    app: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: bookstore:1.0.0
        args: ["config/config.yml"]
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: config
          configMap:
            name: bookstore-config
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore
  ports:
  - name: tcp
    protocol: TCP
    port: 8090
    targetPort: 8090