apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-frontend-deployment
  labels:
    app: books-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-frontend
  template:
    metadata:
      labels:
        app: books-frontend
    spec:
      containers:
      - name: books-frontend
        image: books-frontend:1.0.0
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: books-frontend-service
spec:
  selector:
    app: books-frontend
  ports:
  - name: tcp
    protocol: TCP
    port: 8090
    targetPort: 80